# Generated by Django 5.2.17 on 2026-09-29 23:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Uninvested cash available for new positions.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('risk_profile', models.CharField(choices=[('low', 'Conservative'), ('medium', 'Moderate'), ('high', 'Aggressive')], db_index=True, default='medium', max_length=6)),
                ('is_autonomous', models.BooleanField(default=False, help_text='When True the AI agents may execute trades without human approval.')),
                ('max_trade_allocation_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Maximum share of cash the AI may commit to a single trade (percent).', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('daily_loss_limit_usd', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Portfolio-level stop-loss: max realised loss per UTC day.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('avg_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.portfolio')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('tx_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('executed_by', models.CharField(choices=[('USER', 'User'), ('AI', 'AI Agent')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.portfolio')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasoning', models.TextField(help_text='Full chain-of-thought captured from the reasoning model.')),
                ('action_taken', models.CharField(max_length=255)),
                ('market_sentiment', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], db_index=True, default='NEUTRAL', max_length=20)),
                ('tokens_used', models.IntegerField(default=0)),
                ('api_cost_usd', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='core.portfolio')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_log', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Agent decision log',
                'verbose_name_plural': 'Agent decision logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('balance_usd__gte', 0)), name='portfolio_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('max_trade_allocation_pct__gte', 0), ('max_trade_allocation_pct__lte', 100)), name='portfolio_allocation_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('daily_loss_limit_usd__gte', 0)), name='portfolio_loss_limit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('portfolio', 'ticker'), name='asset_unique_ticker_per_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='asset_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('avg_purchase_price__gte', 0)), name='asset_avg_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', '-timestamp'], name='tx_portfolio_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', 'ticker'], name='tx_portfolio_ticker_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='tx_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='tx_price_positive'),
        ),
        migrations.AddIndex(
            model_name='agentdecisionlog',
            index=models.Index(fields=['portfolio', '-created_at'], name='log_portfolio_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentdecisionlog',
            constraint=models.CheckConstraint(condition=models.Q(('tokens_used__gte', 0)), name='log_tokens_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='agentdecisionlog',
            constraint=models.CheckConstraint(condition=models.Q(('api_cost_usd__gte', 0)), name='log_cost_non_negative'),
        ),
    ]
