# Generated by Django 5.2.17 on 2026-09-30 08:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('link_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_trades', models.BooleanField(default=True)),
                ('notify_recommendations', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram link',
                'verbose_name_plural': 'Telegram links',
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_equity_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cash_balance_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('positions_value_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('unrealised_pnl_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('realised_pnl_today_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio snapshot',
                'verbose_name_plural': 'Portfolio snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['portfolio', '-captured_at'], name='snap_portfolio_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notional_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('sentiment', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('EXECUTED', 'Executed'), ('BLOCKED', 'Blocked by guardrail')], db_index=True, default='PENDING', max_length=10)),
                ('decided_via', models.CharField(blank=True, choices=[('WEB', 'Web dashboard'), ('TELEGRAM', 'Telegram'), ('API', 'REST API'), ('AUTO', 'Automatic')], max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decision_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='core.agentdecisionlog')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.portfolio')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Trade recommendation',
                'verbose_name_plural': 'Trade recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'status', '-created_at'], name='reco_portfolio_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='reco_amount_positive'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='reco_price_positive')],
            },
        ),
    ]
