# Generated by Django 5.2.17 on 2026-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telegramlink_portfoliosnapshot_traderecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdecisionlog',
            name='bear_case',
            field=models.TextField(blank=True, default='', help_text='Bearish argument produced by the risk assessor / short seller.'),
        ),
        migrations.AddField(
            model_name='agentdecisionlog',
            name='bull_case',
            field=models.TextField(blank=True, default='', help_text='Bullish argument produced by the research analyst.'),
        ),
    ]
