# Generated by Django 5.2.17 on 2026-10-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agentdecisionlog_bear_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlink',
            name='link_code_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
