# Generated by Django 5.2.17 on 2026-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_telegramlink_link_code_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdecisionlog',
            name='cache_write_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentdecisionlog',
            name='cached_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentdecisionlog',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentdecisionlog',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
